#include <windows.h>
#include <stdio.h>
#include "../src/tftd_workshop_v2_12_1.c"
static int checks,failures;
#define CHECK(c,m) do{checks++;if(!(c)){failures++;printf("FAIL %s\n",m);}}while(0)
static void panel_screenshot(HWND h,const wchar_t*path){
RECT r;GetClientRect(h,&r);int w=r.right,hh=r.bottom;HDC dc=GetDC(h),mem=CreateCompatibleDC(dc);HBITMAP bm=CreateCompatibleBitmap(dc,w,hh);HGDIOBJ old=SelectObject(mem,bm);FillRect(mem,&r,(HBRUSH)(COLOR_BTNFACE+1));SendMessageW(h,WM_PRINT,(WPARAM)mem,PRF_CLIENT|PRF_CHILDREN|PRF_ERASEBKGND);SelectObject(mem,old);BITMAPINFO bi={0};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=w;bi.bmiHeader.biHeight=-hh;bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;size_t len=(size_t)w*hh*4;void*px=malloc(len);GetDIBits(dc,bm,0,hh,px,&bi,DIB_RGB_COLORS);BITMAPFILEHEADER fh={0};fh.bfType=0x4d42;fh.bfOffBits=sizeof(fh)+sizeof(BITMAPINFOHEADER);fh.bfSize=(DWORD)(fh.bfOffBits+len);FILE*f=_wfopen(path,L"wb");if(f){fwrite(&fh,sizeof(fh),1,f);fwrite(&bi.bmiHeader,sizeof(BITMAPINFOHEADER),1,f);fwrite(px,len,1,f);fclose(f);}free(px);DeleteObject(bm);DeleteDC(mem);ReleaseDC(h,dc);
}
int main(int argc,char**argv){GetFullPathNameW(L"work/languages-test.ini",PATH_CAP,A.configPath,NULL);if(argc==3){int l=atoi(argv[2]);if(!strcmp(argv[1],"write")){i18nLanguage=l;WritePrivateProfileStringW(CFG_SECTION,L"Language",i18nCodes[l],A.configPath);return 0;}i18n_load(A.configPath);printf("fresh language %d: %s\n",l,l==i18nLanguage?"PASS":"FAIL");return l!=i18nLanguage;}
WNDCLASSW wc={0};wc.lpfnWndProc=wndproc;wc.hInstance=GetModuleHandleW(NULL);wc.lpszClassName=L"LanguageTest";RegisterClassW(&wc);A.hwnd=CreateWindowW(wc.lpszClassName,L"Language test",WS_OVERLAPPEDWINDOW,0,0,1600,920,NULL,make_menu(),wc.hInstance,NULL);A.sidebarW=380;A.inspectorW=280;A.zoom=1;A.selectedLib=-1;A.clientW=1584;A.clientH=881;ensure_backbuf(A.clientW,A.clientH);CHECK(scene_alloc(20,20,2),"scene fixture");A.scene.dirty=1;SceneCell*scene=A.scene.cells;A.currentZ=1;A.showAllBelow=1;A.showComplete=0;A.showGrid=0;
HWND child=CreateWindowW(L"STATIC",L"Enregistrer",WS_CHILD|WS_VISIBLE,10,10,200,40,A.hwnd,NULL,wc.hInstance,NULL);HWND editable=CreateWindowW(L"EDIT",L"Enregistrer",WS_CHILD|WS_VISIBLE,10,60,200,40,A.hwnd,NULL,wc.hInstance,NULL);HWND dynamic=CreateWindowW(L"STATIC",L"",WS_CHILD|WS_VISIBLE,10,110,400,40,A.hwnd,NULL,wc.hInstance,NULL);wchar_t line[512];_snwprintf(line,511,tr(L"Nouvelle MAP %dx%dx%d creee."),20,30,2);SetWindowTextW(dynamic,line);tutorial_open();
for(int l=0;l<4;l++){handle_command(IDM_LANGUAGE_BASE+l);CHECK(i18nLanguage==l,"language selected");CHECK(A.scene.cells==scene&&A.scene.dirty&&A.currentZ==1&&A.showAllBelow&&!A.showComplete&&!A.showGrid,"language preserves document and view");GetWindowTextW(child,line,512);CHECK(!wcscmp(line,tr(L"Enregistrer")),"open static control translated");GetWindowTextW(editable,line,512);CHECK(!wcscmp(line,L"Enregistrer"),"user text untouched");CHECK(SendMessageW(tutorialList,LB_GETCOUNT,0,0)==8,"eight tutorial chapters");GetWindowTextW(dynamic,line,512);wchar_t expect[512];_snwprintf(expect,511,tr(L"Nouvelle MAP %dx%dx%d creee."),20,30,2);CHECK(!wcscmp(line,expect),"formatted open control translated");
for(int chapter=0;chapter<8;chapter++){SendMessageW(tutorialList,LB_SETCURSEL,chapter,0);SendMessageW(tutorialWindow,WM_COMMAND,MAKEWPARAM(1,LBN_SELCHANGE),0);int length=GetWindowTextLengthW(tutorialText);CHECK(length>500,"translated chapter available");}
wchar_t path[80];_snwprintf(path,79,L"work/tutorial-%d.bmp",l);panel_screenshot(tutorialWindow,path);HMENU menu=GetMenu(A.hwnd);int checked=0;for(int k=0;k<GetMenuItemCount(menu);k++){HMENU sub=GetSubMenu(menu,k);if(!sub)continue;for(int j=0;j<GetMenuItemCount(sub);j++)if(GetMenuItemID(sub,j)==(UINT)(IDM_LANGUAGE_BASE+l))checked=(GetMenuState(sub,IDM_LANGUAGE_BASE+l,MF_BYCOMMAND)&MF_CHECKED)!=0;}CHECK(checked,"selected language checked in menu");}
handle_command(IDM_LANGUAGE_BASE);GetWindowTextW(child,line,512);CHECK(!wcscmp(line,L"Enregistrer"),"switch back to French");WritePrivateProfileStringW(CFG_SECTION,L"Language",L"bad",A.configPath);i18n_load(A.configPath);CHECK(i18nLanguage==0,"unknown preference falls back to French");CHECK(!wcscmp(tr(L"C:/SAND/015.png"),L"C:/SAND/015.png"),"resource path unchanged");DestroyWindow(tutorialWindow);scene_free();printf("RESULT %d/%d language/tutorial checks\n",checks-failures,checks);return failures?1:0;}

