#include <windows.h>
#include <stdio.h>
static int dialogs,dialogAnswer=IDNO;
static int test_message(HWND h,LPCWSTR t,LPCWSTR c,UINT u){(void)h;(void)c;(void)u;dialogs++;wprintf(L"DIALOG: %ls\n",t);return dialogAnswer;}
#define MessageBoxW test_message
#include "../src/tftd_workshop_v2_12_1.c"
static int failures,checks;
#define CHECK(c,m) do{int result=!!(c);checks++;printf("[%s] %s\n",result?"PASS":"FAIL",m);if(!result)failures++;}while(0)
static uint64_t render_hash(void){clear_back(0xff091014);draw_map();uint64_t h=1469598103934665603ULL;for(int i=0;i<A.backW*A.backH;i++){h^=A.backbuf[i];h*=1099511628211ULL;}return h;}
static void screenshot(const wchar_t*path){HDC dc=GetDC(A.hwnd),mem=CreateCompatibleDC(dc);HBITMAP bmp=CreateCompatibleBitmap(dc,A.clientW,A.clientH);HGDIOBJ old=SelectObject(mem,bmp);paint(A.hwnd,mem);SelectObject(mem,old);BITMAPINFO bi=A.bmi;size_t len=(size_t)A.clientW*A.clientH*4;void*px=malloc(len);GetDIBits(dc,bmp,0,A.clientH,px,&bi,DIB_RGB_COLORS);BITMAPFILEHEADER fh={0};fh.bfType=0x4d42;fh.bfOffBits=sizeof(fh)+sizeof(BITMAPINFOHEADER);fh.bfSize=(DWORD)(fh.bfOffBits+len);FILE*f=_wfopen(path,L"wb");if(f){fwrite(&fh,sizeof(fh),1,f);fwrite(&bi.bmiHeader,sizeof(BITMAPINFOHEADER),1,f);fwrite(px,len,1,f);fclose(f);}free(px);DeleteObject(bmp);DeleteDC(mem);ReleaseDC(A.hwnd,dc);}


static void panel_screenshot(HWND h,const wchar_t*path){
RECT r;GetClientRect(h,&r);int w=r.right,hh=r.bottom;HDC dc=GetDC(h),mem=CreateCompatibleDC(dc);HBITMAP bm=CreateCompatibleBitmap(dc,w,hh);HGDIOBJ old=SelectObject(mem,bm);FillRect(mem,&r,(HBRUSH)(COLOR_BTNFACE+1));SendMessageW(h,WM_PRINT,(WPARAM)mem,PRF_CLIENT|PRF_CHILDREN|PRF_ERASEBKGND);SelectObject(mem,old);BITMAPINFO bi={0};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=w;bi.bmiHeader.biHeight=-hh;bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;size_t len=(size_t)w*hh*4;void*px=malloc(len);GetDIBits(dc,bm,0,hh,px,&bi,DIB_RGB_COLORS);BITMAPFILEHEADER fh={0};fh.bfType=0x4d42;fh.bfOffBits=sizeof(fh)+sizeof(BITMAPINFOHEADER);fh.bfSize=(DWORD)(fh.bfOffBits+len);FILE*f=_wfopen(path,L"wb");if(f){fwrite(&fh,sizeof(fh),1,f);fwrite(&bi.bmiHeader,sizeof(BITMAPINFOHEADER),1,f);fwrite(px,len,1,f);fclose(f);}free(px);DeleteObject(bm);DeleteDC(mem);ReleaseDC(h,dc);
}
static uint64_t scene_hash(void){uint64_t h=1469598103934665603ULL;uint8_t*b=(uint8_t*)A.scene.cells;size_t n=(size_t)A.scene.x*A.scene.y*A.scene.z*sizeof(SceneCell);for(size_t i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}size_t bytes=scene_geo_bytes(&A.scene);if(bytes){b=calloc(bytes,1);scene_geo_write(b,&A.scene);for(size_t j=0;j<bytes;j++){h^=b[j];h*=1099511628211ULL;}free(b);}return h;}

static int rock_complete(int x,int y,int z,int lib,int local){for(int u=0;u<5;u++){const ProcRockUnit*a=&procRockUnits[u];for(int k=0;k<a->count;k++)if(a->ids[k]==local){int ox=x-k%a->w,oy=y-k/a->w,ok=1;for(int j=0;j<a->count;j++){SceneCell*c=scene_cell_at(ox+j%a->w,oy+j/a->w,z);if(!c||c->lib[3]!=lib||c->local[3]!=a->ids[j])ok=0;}if(ok)return 1;}}return 0;}
static void dump_geo(int seed){char path[100];snprintf(path,100,"work/generated-geo-%03d.json",seed);FILE*f=fopen(path,"w");if(!f)return;fprintf(f,"{\"format\":\"GEO_TERRAIN_SCENE\",\"version\":\"1.2.0\",\"allowCrease\":false,\"requireGrounded\":true,\"instances\":[");for(int n=0;n<A.scene.geoCount;n++){GeoInstance*i=&A.scene.geo[n];fprintf(f,"%s{\"id\":\"%s\",\"uid\":\"%s\",\"x\":%d,\"y\":%d,\"z\":%.9g,\"rotation\":%d,\"mirror\":%s,\"role\":\"%s\"",n?",":"",geo_meshes[i->mesh].id,i->uid,i->x,i->y,i->z,i->rotation,i->mirror?"true":"false",i->support?"support":"terrain");if(i->dynamic){fprintf(f,",\"params\":{\"kind\":\"bezier_patch\",\"controls\":[");for(int k=0;k<16;k++)fprintf(f,"%s%.17g",k?",":"",i->dynamic->controls[k]);fprintf(f,"]}");}fprintf(f,"}");}fprintf(f,"]}");fclose(f);}
int main(int argc,char**argv){
GdiplusStartupInput gdsi={0};gdsi.GdiplusVersion=1;GdiplusStartup(&gGdiPlusToken,&gdsi,NULL);
if(argc!=4){printf("Usage: procedural.exe TFTD OXCE_XCOM2 MIRROR_MOD\n");return 2;}
MultiByteToWideChar(CP_UTF8,0,argv[1],-1,A.tftdRoot,PATH_CAP);MultiByteToWideChar(CP_UTF8,0,argv[2],-1,A.oxceRoot,PATH_CAP);
A.sidebarW=240;A.inspectorW=280;A.zoom=1;A.brushSize=1;A.selectedLib=-1;A.expandedLib=A.expandedActive=-1;A.selectedMap=-1;A.autoProfileIndex=-1;
WNDCLASSW wc={0};wc.lpfnWndProc=wndproc;wc.hInstance=GetModuleHandleW(NULL);wc.lpszClassName=L"ProcTest";RegisterClassW(&wc);A.hwnd=CreateWindowW(wc.lpszClassName,L"Procedural tests",WS_OVERLAPPEDWINDOW,0,0,2560,1500,NULL,make_menu(),wc.hInstance,NULL);RECT cr;GetClientRect(A.hwnd,&cr);A.clientW=cr.right;A.clientH=cr.bottom;ensure_backbuf(A.clientW,A.clientH);
wcscpy(A.modsRoot,L"C:/OpenXcom Extended/user/mods");default_palette();scan_dir_recursive(A.tftdRoot,SRC_TFTD,0,L"TFTD ORIGINAL");scan_dir_recursive(A.oxceRoot,SRC_OXCE,0,L"OXCE STANDARD");wchar_t mirrorRoot[PATH_CAP];MultiByteToWideChar(CP_UTF8,0,argv[3],-1,mirrorRoot,PATH_CAP);scan_dir_recursive(mirrorRoot,SRC_MOD,0,L"JM_USO_SYMETRIE");library_sort();map_sort();map_refresh_profiles();
CHECK(proc_catalog_build(),"original resource catalog resolves");printf("CATALOG %d\n",procMotifCount);for(int i=0;i<procMotifCount;i++)printf("MOTIF %ls %dx%dx%d parts=%d relief=%d\n",procMotifs[i].name,procMotifs[i].w,procMotifs[i].h,procMotifs[i].z,procMotifs[i].count,procMotifs[i].relief);

BlueprintCapturePart*hp=(BlueprintCapturePart*)calloc(PROC_MAX_PARTS,sizeof(*hp));int db=library_find_name_ctx(L"DEBRIS",SRC_TFTD,L"TFTD ORIGINAL"),heightOk=1;
for(int peak=3;peak<=6;peak++)for(int w=2*peak+2;w<=2*peak+4;w++)for(int h=2*peak+2;h<=2*peak+4;h++){int n=0;if(!proc_hill_parts(w,h,peak,db,hp,&n)){heightOk=0;continue;}for(int y=0;y<h;y++)for(int x=0;x<w;x++){float top[4]={-999,-999,-999,-999};for(int i=0;i<n;i++)if(hp[i].x==x&&hp[i].y==y){float hh[4];if(!rh_profile(hp[i].lib,hp[i].local,hh)){heightOk=0;continue;}for(int k=0;k<4;k++){float v=hp[i].z*24-hh[k];if(v>top[k])top[k]=v;}}int expect[4]={proc_hill_height(x,y,w,h,peak),proc_hill_height(x+1,y,w,h,peak),proc_hill_height(x+1,y+1,w,h,peak),proc_hill_height(x,y+1,w,h,peak)};for(int k=0;k<4;k++)if(top[k]!=expect[k]*8)heightOk=0;}}
int lowOk=1;for(int w=5;w<=10;w++)for(int h=5;h<=10;h++)for(int v=0;v<2;v++){int n=0;if(!proc_low_parts(w,h,v,hp,&n)||!n)lowOk=0;for(int j=0;j<n;j++){float hh[4];if(hp[j].z!=0||!rh_profile(hp[j].lib,hp[j].local,hh))lowOk=0;for(int k=0;k<4;k++)if(hh[k]>0||hh[k]<-8)lowOk=0;}}CHECK(lowOk,"72 asymmetric small dune shapes use only valid ground-level SAND pieces");
free(hp);CHECK(heightOk,"36 synthesized reliefs match shared world heights at every corner across Z");
CHECK(procMotifCount>=6,"observed motifs plus Bible assemblies available");
ProcRecipe r={.width=60,.height=60,.density=2,.relief=1,.gap=2,.craft=-1,.uso=-1,.seed=27092026};ProcReport report;
CHECK(proc_generate(&r,&report),"default generation succeeds");printf("RELIEFS historical=%d lowZ0=%d upper=%d\n",report.historical,report.lowReliefs,report.upperReliefs);CHECK(report.historical==2&&report.lowReliefs>=5&&report.upperReliefs==1,"dense 60x60 contains two complex historical reliefs, many low dunes and true upper terrain");printf("ECOLOGY weeds=%d rocks=%d wrecks=%d\n",report.weeds,report.rocks,report.wrecks);printf("DEFAULT placed=%d relief=%d open=%d/%d\n",report.placed,report.reliefs,report.open,report.total);CHECK(report.placed>0,"actual existing assemblies placed");CHECK(report.reliefs>0,"default relief option places a historical relief");CHECK(report.weeds>=90&&report.rocks>=35,"maximum richness produces substantial historical decoration");uint64_t first=scene_hash();CHECK(proc_generate(&r,&report)&&first==scene_hash(),"same seed reproduces identical scene");
int denseCount=report.weeds+report.rocks;ProcRecipe lighter=r;lighter.density=0;CHECK(proc_generate(&lighter,&report)&&denseCount>2*(report.weeds+report.rocks),"maximum richness has more than twice the light-mode vegetation and rocks at equal seed and size");CHECK(proc_generate(&r,&report)&&scene_hash()==first,"return to dense recipe restores its exact scene");
int historicalExact=0;for(int mi=0;mi<procMotifCount;mi++){ProcMotif*m=&procMotifs[mi];if(!m->relief)continue;int found=0;for(int y=0;y<=A.scene.y-m->h&&!found;y++)for(int x=0;x<=A.scene.x-m->w&&!found;x++){int ok=1;for(int j=0;j<m->count&&ok;j++){BlueprintCapturePart*p=&m->parts[j];float hh[4];if(!rh_profile(p->lib,p->local,hh))continue;SceneCell*c=scene_cell_at(x+p->x,y+p->y,p->z);if(!c||c->lib[p->layer]!=p->lib||c->local[p->layer]!=p->local)ok=0;}if(ok)found=1;}historicalExact+=found;}CHECK(historicalExact==2,"both historical terrain compositions preserved piece for piece, excluding nonterrain effects and decor");
CHECK(scene_save_project_file(L"work/sand-procedural-27092026.JMW"),"generated scene saves as JMW4 with GEO parameters");CHECK(scene_load_project_file(L"work/sand-procedural-27092026.JMW")&&scene_hash()==first,"JMW round trip preserves every layer and level");
size_t gb=scene_geo_bytes(&A.scene);uint8_t*rawgeo=calloc(gb,1);scene_geo_write(rawgeo,&A.scene);SceneDoc parsed={.x=A.scene.x,.y=A.scene.y,.z=A.scene.z};CHECK(scene_geo_read(rawgeo,gb,&parsed),"GEO binary layer reads independently");scene_geo_free(&parsed);CHECK(!scene_geo_read(rawgeo,gb-1,&parsed),"truncated GEO layer rejected");scene_geo_free(&parsed);SceneGeoRecord*bad=(SceneGeoRecord*)(rawgeo+sizeof(SceneGeoHeader));float savedZ=bad->z;bad->z=NAN;CHECK(!scene_geo_read(rawgeo,gb,&parsed),"nonfinite GEO anchor rejected");scene_geo_free(&parsed);bad->z=savedZ;int savedX=bad->x;bad->x=A.scene.x;CHECK(!scene_geo_read(rawgeo,gb,&parsed),"outside GEO anchor rejected");scene_geo_free(&parsed);bad->x=savedX;free(rawgeo);int appui=1;for(int n=0;n<A.scene.geoDecorCount;n++){GeoDecor*d=&A.scene.geoDecor[n];int found=0;for(int j=0;j<A.scene.geoCount;j++){GeoInstance*i=&A.scene.geo[j];const GeoPorts*p=i->dynamic?&i->dynamic->ports:&geo_ports[i->mesh];if(i->x==d->x&&i->y==d->y&&!i->support&&!strstr(i->uid,"_access")&&fabs(p->maxz-p->minz)<1e-8&&fabs(d->z-i->z-p->maxz)<1e-7)found=1;}if(!found)appui=0;}CHECK(appui&&report.upperDecor>0,"upper decorations sit on horizontal platforms outside reserved access");int oldDialogs=dialogs;open_export_wizard();CHECK(dialogs==oldDialogs+1&&!EUI.hwnd,"GEO export refused before opening export wizard");dialogs=oldDialogs;
A.currentZ=0;A.showComplete=1;A.showGrid=0;A.panY=150;screenshot(L"work/procedural-normal.bmp");CHECK(rhTextures[0].p&&rhTextures[1].p,"installed SAND materials loaded for GEO");CHECK(render_hash()!=0,"actual Workshop renderer renders generated scene");A.viewMode=1;A.panX=A.panY=0;screenshot(L"work/procedural-plan.bmp");A.viewMode=0;
int ecology=1,spacing=1,multi=1,sparse=1;int all=1,valid=1,floors=1,different=0,reliefs=0,minimum=100,impacts=0,realZ=1;
for(int seed=0;seed<100;seed++){r.seed=(uint32_t)seed;r.density=seed%3;r.relief=seed%2;r.gap=2+seed%4;r.width=30+seed%4*10;r.height=40+seed%3*10;if(!proc_generate(&r,&report)){all=0;printf("FAILED SEED %d %ls\n",seed,procError);continue;}if(r.relief)dump_geo(seed);if(scene_hash()!=first)different++;reliefs+=report.reliefs;if(r.relief&&(report.lowReliefs<1||report.upperReliefs<1))multi=0;if(report.placed-report.reliefs>406)sparse=0;int percent=report.open*100/report.total;if(percent<minimum)minimum=percent;
 for(int i=0;i<A.scene.x*A.scene.y;i++)if(A.scene.cells[i].lib[0]<0)floors=0;
 int above=0;for(size_t i=0,n=(size_t)A.scene.x*A.scene.y*A.scene.z;i<n;i++)for(int p=0;p<4;p++){int li=A.scene.cells[i].lib[p],lo=A.scene.cells[i].local[p];if(li>=0&&(li>=A.libraryCount||lo<0||lo>=A.library[li].mcdCount))valid=0;if(li==procSand&&(mcd_frame(li,lo)==18||mcd_frame(li,lo)==19))impacts++;if(i>=(size_t)A.scene.x*A.scene.y&&li>=0)above++;}
 int weedLib=library_find_name_ctx(L"WEEDS",SRC_TFTD,L"TFTD ORIGINAL"),rockLib=library_find_name_ctx(L"ROCKS",SRC_TFTD,L"TFTD ORIGINAL"),wc=0,rc=0;
 for(int i=0;i<A.scene.x*A.scene.y;i++){SceneCell*c=&A.scene.cells[i];if(c->lib[3]==weedLib){wc++;int lo=c->local[3];if(lo!=0&&lo!=3&&lo!=5&&lo!=8)ecology=0;}if(c->lib[3]==rockLib){rc++;int lo=c->local[3];if(!rock_complete(i%A.scene.x,i/A.scene.x,0,rockLib,lo))ecology=0;for(int j=0;j<i;j++)if(lo<=1&&A.scene.cells[j].lib[3]==rockLib&&A.scene.cells[j].local[3]<=1){int dx=i%A.scene.x-j%A.scene.x,dy=i/A.scene.x-j/A.scene.x,d=lo==A.scene.cells[j].local[3]?(r.density==2?6:9):(r.density==2?3:4);if(dx*dx+dy*dy<d*d)spacing=0;}}}
 for(int zz=1;zz<A.scene.z;zz++)for(int j=0;j<A.scene.x*A.scene.y;j++){SceneCell*c=&A.scene.cells[zz*A.scene.x*A.scene.y+j];if(c->lib[3]==weedLib)wc++;if(c->lib[3]==rockLib){rc++;if(!rock_complete(j%A.scene.x,j/A.scene.x,zz,rockLib,c->local[3]))ecology=0;}}for(int j=0;j<A.scene.geoDecorCount;j++){if(A.scene.geoDecor[j].family)rc++;else wc++;}if(wc!=report.weeds||rc!=report.rocks||report.wrecks>6)ecology=0;
 if(!r.relief&&report.reliefs)valid=0;if(r.relief&&!above){int high=0;for(int j=0;j<A.scene.geoCount;j++)if(!A.scene.geo[j].support&&A.scene.geo[j].z>=1)high++;if(!high)realZ=0;}
}
CHECK(ecology,"every rock fragment belongs to a complete allowed unit; counts match report");CHECK(spacing,"autonomous rocks retain isolation across 100 seeds");CHECK(impacts==0,"no SAND frame 018 or 019 anywhere in 100 generated terrains");CHECK(realZ,"every successful relief recipe has occupied upper Z, not just allocated levels");CHECK(multi,"all relief recipes mix low dunes and true upper terrain");CHECK(sparse,"decoration count obeys independent sparse budget");CHECK(all,"100 seeds across sizes/densities/passages succeed and pass connected-space check");CHECK(valid,"all generated references valid and flat mode excludes relief");CHECK(floors,"every ground cell has a floor");CHECK(different==100,"different recipes produce different scenes");CHECK(reliefs>0,"historical relief assemblies actually used");CHECK(minimum>=30,"at least 30 percent outside terrain and decor footprints without ships");printf("SERIES relief motifs=%d min open=%d%%\n",reliefs,minimum);
SceneCell*old=A.scene.cells;uint64_t before=scene_hash();int undo=A.undoCount;r.width=5;CHECK(!proc_generate(&r,&report)&&old==A.scene.cells&&before==scene_hash()&&undo==A.undoCount,"invalid dimensions preserve scene and undo");
r.width=20;r.height=20;r.craft=exact_map_by_name(L"TRITON",SRC_TFTD,L"TFTD ORIGINAL");r.uso=exact_map_by_name(L"UFO08",SRC_TFTD,L"TFTD ORIGINAL");CHECK(r.craft>=0&&r.uso>=0,"original craft and UFO08 fixtures available");CHECK(!proc_generate(&r,&report)&&old==A.scene.cells&&before==scene_hash(),"oversized ship fails without replacing current work");
r.width=80;r.height=80;r.gap=3;r.density=1;r.relief=1;r.seed=27092026;CHECK(proc_generate(&r,&report),"craft and full UFO08 can be placed with clear margins");CHECK(A.scene.craftW>0&&A.scene.usoSlotActive&&A.scene.usoInserted,"both ship reservations recorded");
SceneDoc ship={0};int exact=proc_read_map(r.uso,&ship);for(int z=0;z<ship.z;z++)for(int y=0;y<ship.y;y++)for(int x=0;x<ship.x;x++){SceneCell*a=&ship.cells[(z*ship.y+y)*ship.x+x],*b=scene_cell_at(A.scene.usoSlotX+x,A.scene.usoSlotY+y,z);for(int p=0;p<4;p++)if(a->lib[p]>=0&&(!b||a->lib[p]!=b->lib[p]||a->local[p]!=b->local[p]))exact=0;}free(ship.cells);CHECK(exact,"all occupied UFO08 layers and Z copied exactly");
CHECK(scene_save_project_file(L"work/sand-triton-ufo08.JMW"),"ship example saved");

int shipsOk=1,shipsTested=0;
for(int sym=0;sym<2;sym++)for(int id=1;id<=8;id++){wchar_t name[32];_snwprintf(name,31,sym?L"JMUFO%02d":L"UFO%02d",id);r.uso=exact_map_by_name(name,sym?SRC_MOD:SRC_TFTD,sym?L"JM_USO_SYMETRIE":L"TFTD ORIGINAL");if(r.uso<0||!proc_generate(&r,&report)){shipsOk=0;continue;}shipsTested++;SceneDoc source={0};if(!proc_read_map(r.uso,&source)){shipsOk=0;continue;}for(int z=0;z<source.z;z++)for(int y=0;y<source.y;y++)for(int x=0;x<source.x;x++){SceneCell*a=&source.cells[(z*source.y+y)*source.x+x],*b=scene_cell_at(A.scene.usoSlotX+x,A.scene.usoSlotY+y,z);for(int p=0;p<4;p++)if(a->lib[p]>=0&&(!b||b->lib[p]!=a->lib[p]||b->local[p]!=a->local[p]))shipsOk=0;}free(source.cells);}
CHECK(shipsOk&&shipsTested==16,"eight original and eight mirrored USOs preserve every source part");CHECK(scene_save_project_file(L"work/sand-triton-chaland-sym.JMW"),"mirrored ship example saved");
WNDCLASSW pw={0};pw.lpfnWndProc=proc_wndproc;pw.hInstance=wc.hInstance;pw.lpszClassName=L"ProcPanelTest";RegisterClassW(&pw);HWND panel=CreateWindowW(pw.lpszClassName,L"Procedural",WS_OVERLAPPEDWINDOW,0,0,636,630,A.hwnd,NULL,wc.hInstance,NULL);CHECK(PUI.width&&PUI.seed&&PUI.report,"generator controls created");panel_screenshot(panel,L"work/procedural-panel.bmp");SetWindowTextW(PUI.seed,L"4294967296");before=scene_hash();proc_ui_generate();CHECK(before==scene_hash(),"overflowing seed rejected before scene change");DestroyWindow(panel);

CHECK(dialogs==0,"no unexpected modal dialogs");
A.scene.dirty=1;dialogAnswer=IDCANCEL;before=scene_hash();CHECK(!proc_can_replace(A.hwnd)&&scene_hash()==before&&A.scene.dirty,"cancel retains unsaved generated scene");dialogAnswer=IDNO;CHECK(proc_can_replace(A.hwnd),"explicit discard permits replacement");A.scene.dirty=0;
r.craft=r.uso=-1;r.width=37;r.height=43;r.seed=UINT32_MAX;CHECK(proc_generate(&r,&report),"non-multiple-of-ten dimensions and maximum seed accepted");
r.seed=0;CHECK(proc_generate(&r,&report),"zero seed accepted");before=scene_hash();CHECK(proc_generate(&r,&report)&&before==scene_hash(),"zero seed is reproducible");

GetFullPathNameW(L"work/view-preferences.ini",PATH_CAP,A.configPath,NULL);config_save();
for(int mode=0;mode<3;mode++){
 set_normal_visibility(mode);int below=A.showAllBelow,complete=A.showComplete;
 CHECK(proc_generate(&r,&report)&&A.showAllBelow==below&&A.showComplete==complete,"generation retains each of three visibility choices");
 CHECK(scene_save_project_file(L"work/view-test.JMW"),"visibility test project saved");
 CHECK(scene_load_project_file(L"work/view-test.JMW")&&A.showAllBelow==below&&A.showComplete==complete,"opening project retains visibility choice");
 CHECK(new_map(10,10,3)&&A.showAllBelow==below&&A.showComplete==complete,"new map retains visibility choice");
 A.showAllBelow=0;A.showComplete=0;config_load();
 CHECK(A.showComplete==(mode==2)&&A.showAllBelow==(mode!=0),"saved visibility restored from isolated preferences");
}
CHECK(scene_alloc(20,20,2),"reservation overlay fixture created");A.currentZ=0;A.hoverValid=0;A.scene.craftX=0;A.scene.craftY=0;A.scene.craftW=A.scene.craftH=10;A.scene.usoSlotActive=1;A.scene.usoSlotX=10;A.scene.usoSlotY=0;A.scene.usoSlotW=A.scene.usoSlotH=10;
A.scene.macroFlags[0]=SCENE_MACRO_CRAFT|SCENE_MACRO_UNDERLAY;A.scene.macroFlags[1]=SCENE_MACRO_USO|SCENE_MACRO_UNDERLAY;
for(int view=0;view<3;view++){
 A.viewMode=view;A.showGrid=0;uint64_t hidden=render_hash();A.showGrid=1;uint64_t shown=render_hash();
 A.scene.macroFlags[0]=A.scene.macroFlags[1]=0;A.scene.craftW=0;A.scene.usoSlotActive=0;
 CHECK(render_hash()!=shown,"grid enabled shows ship reservation overlays in each view");A.showGrid=0;CHECK(render_hash()==hidden,"grid disabled removes reservations and underlay markers in each view");
 A.scene.macroFlags[0]=SCENE_MACRO_CRAFT|SCENE_MACRO_UNDERLAY;A.scene.macroFlags[1]=SCENE_MACRO_USO|SCENE_MACRO_UNDERLAY;A.scene.craftW=10;A.scene.usoSlotActive=1;
}
HMENU menus=make_menu();int proceduralEntries=0,procIsDirect=0;for(int i=0;i<GetMenuItemCount(menus);i++){if(GetMenuItemID(menus,i)==IDM_PROCEDURAL){proceduralEntries++;procIsDirect=GetSubMenu(menus,i)==NULL;}}CHECK(proceduralEntries==1&&procIsDirect,"single direct procedural entry without version submenu");DestroyMenu(menus);
printf("RESULT %d/%d checks passed\n",checks-failures,checks);return failures?1:0;
}
