#include <windows.h>
#include <stdio.h>
static int dialogs;
static int test_message(HWND h,LPCWSTR t,LPCWSTR c,UINT u){(void)h;(void)c;(void)u;dialogs++;wprintf(L"DIALOG: %ls\n",t);return IDNO;}
#define MessageBoxW test_message
#include "../src/tftd_workshop_v2_12_1.c"
static int failures,checks;
#define CHECK(c,m) do{int result=!!(c);checks++;printf("[%s] %s\n",result?"PASS":"FAIL",m);if(!result)failures++;}while(0)
static uint64_t render_hash(void){clear_back(0xff091014);draw_map();uint64_t h=1469598103934665603ULL;for(int i=0;i<A.backW*A.backH;i++){h^=A.backbuf[i];h*=1099511628211ULL;}return h;}
static void screenshot(const wchar_t*path){HDC dc=GetDC(A.hwnd),mem=CreateCompatibleDC(dc);HBITMAP bmp=CreateCompatibleBitmap(dc,A.clientW,A.clientH);HGDIOBJ old=SelectObject(mem,bmp);paint(A.hwnd,mem);SelectObject(mem,old);BITMAPINFO bi=A.bmi;size_t len=(size_t)A.clientW*A.clientH*4;void*px=malloc(len);GetDIBits(dc,bmp,0,A.clientH,px,&bi,DIB_RGB_COLORS);BITMAPFILEHEADER fh={0};fh.bfType=0x4d42;fh.bfOffBits=sizeof(fh)+sizeof(BITMAPINFOHEADER);fh.bfSize=(DWORD)(fh.bfOffBits+len);FILE*f=_wfopen(path,L"wb");if(f){fwrite(&fh,sizeof(fh),1,f);fwrite(&bi.bmiHeader,sizeof(BITMAPINFOHEADER),1,f);fwrite(px,len,1,f);fclose(f);}free(px);DeleteObject(bmp);DeleteDC(mem);ReleaseDC(A.hwnd,dc);}
int main(int argc,char**argv){
if(argc!=3){printf("Usage: regression.exe TFTD_DIRECTORY OXCE_XCOM2_DIRECTORY\n");return 2;}
MultiByteToWideChar(CP_UTF8,0,argv[1],-1,A.tftdRoot,PATH_CAP);MultiByteToWideChar(CP_UTF8,0,argv[2],-1,A.oxceRoot,PATH_CAP);
A.sidebarW=300;A.inspectorW=300;A.zoom=1;A.brushSize=1;A.selectedLib=-1;A.expandedLib=A.expandedActive=-1;A.selectedMap=-1;A.autoProfileIndex=-1;
WNDCLASSW wc={0};wc.lpfnWndProc=wndproc;wc.hInstance=GetModuleHandleW(NULL);wc.lpszClassName=L"WorkshopRegressionMain";RegisterClassW(&wc);A.hwnd=CreateWindowW(wc.lpszClassName,L"Workshop regression",WS_OVERLAPPEDWINDOW,0,0,1620,1039,NULL,make_menu(),wc.hInstance,NULL);RECT client;GetClientRect(A.hwnd,&client);A.clientW=client.right;A.clientH=client.bottom;CHECK(A.clientW>1000&&A.clientH>600,"hidden test window has a real viewport");
default_palette();scan_dir_recursive(A.tftdRoot,SRC_TFTD,0,L"TFTD ORIGINAL");scan_dir_recursive(A.oxceRoot,SRC_OXCE,0,L"OXCE STANDARD");library_sort();map_sort();map_refresh_profiles();
printf("INDEX maps=%d terrains=%d scripts=%d\n",A.mapCount,gOxcTerrainCount,gOxcScriptCount);
wc.lpfnWndProc=composer_wndproc;wc.lpszClassName=L"WorkshopRegressionComposer";RegisterClassW(&wc);CUI.hwnd=CreateWindowW(wc.lpszClassName,L"Test",WS_OVERLAPPED,0,0,620,485,A.hwnd,NULL,wc.hInstance,NULL);populate_composer_combos();
int shipChoices=0;int count=(int)SendMessageW(CUI.scriptCombo,CB_GETCOUNT,0,0);
for(int i=0;i<count;i++){if(composerPresetMap[i]<0)continue;shipChoices++;SendMessageW(CUI.scriptCombo,CB_SETCURSEL,i,0);composer_update_info(1);int mi=composerPresetMap[i];wchar_t family[96];map_prefix(A.maps[mi].name,family,96);int ts=(int)SendMessageW(CUI.terrainCombo,CB_GETCURSEL,0,0);int selected=(int)SendMessageW(CUI.terrainCombo,CB_GETITEMDATA,ts,0);wchar_t selectedFamily[96];map_prefix(A.maps[selected].name,selectedFamily,96);CHECK(!_wcsicmp(family,selectedFamily),"ship preset selects its terrain");CHECK(edit_get_int(CUI.widthEdit,0)==30&&edit_get_int(CUI.lengthEdit,0)==70,"ship preset dimensions 30 x 70");for(int seed=1;seed<=3;seed++){wchar_t n[20];_snwprintf(n,19,L"%d",seed*41);SetWindowTextW(CUI.seedEdit,n);int ok=composer_generate_exact();wprintf(L"GENERATION %ls seed=%ls result=%d\n",family,n,ok);CHECK(ok,"complete ship generation with actual MAP files");CHECK(A.scene.x==30&&A.scene.y==70,"generated scene dimensions");}}
CHECK(shipChoices==4,"cruise and cargo parts 1 and 2 are explicit choices");
int ti=exact_terrain_for_family(L"LINERT",SRC_OXCE,L""),si=-1;for(int i=0;i<gOxcScriptCount;i++)if(!_wcsicmp(gOxcScripts[i].name,L"SHIP_P1"))si=i;CHECK(ti>=0&&si>=0,"reference cruise terrain and recipe indexed");OxcMapScriptDef*ship=&gOxcScripts[si];OxcCommandDef*missing=NULL;for(int i=0;i<ship->commandCount;i++){OxcCommandDef*c=&gOxcCommands[ship->firstCommand+i];if(c->type==OXC_CMD_ADDBLOCK&&c->sizeY==7)missing=c;}CHECK(missing!=NULL,"optional 30 x 70 attempt found");wchar_t why[300];CHECK(exact_script_terrain_compatible(ship,ti,why,300),"optional absent block does not reject valid cruise recipe");if(missing){missing->canBeSkipped=0;CHECK(!exact_script_terrain_compatible(ship,ti,why,300),"explicit mandatory missing block is still rejected");missing->canBeSkipped=1;}

for(int row=0;row<count;row++){SendMessageW(CUI.scriptCombo,CB_SETCURSEL,row,0);int idx=composer_selected_script_index();if(idx>=0&&!_wcsicmp(gOxcScripts[idx].name,L"ALIEN_COLONY_P1")){composer_update_info(1);int selected=(int)SendMessageW(CUI.terrainCombo,CB_GETITEMDATA,SendMessageW(CUI.terrainCombo,CB_GETCURSEL,0,0),0);wchar_t name[96];map_prefix(A.maps[selected].name,name,96);CHECK(!_wcsicmp(name,L"ENTRY"),"colony recipe still auto-selects ENTRY rather than partial matches");break;}}
ensure_backbuf(A.clientW,A.clientH);A.showGrid=0;A.currentZ=A.scene.z-1;A.showAllBelow=1;A.showComplete=0;uint64_t full=render_hash();A.currentZ=0;A.showComplete=1;CHECK(render_hash()==full,"scene complete view remains identical when descending to Z0");CHECK(A.currentZ==0,"scene render preserves active editing Z");A.showComplete=0;CHECK(render_hash()!=full,"scene complete view can be switched off");scene_free();
int mi=exact_map_by_name(L"LINERT00",SRC_OXCE,L"");CHECK(mi>=0&&load_map_file(A.maps[mi].path),"load cruise MAP with indexed datasets");A.currentZ=A.map.z-1;A.showAllBelow=1;A.showComplete=0;full=render_hash();A.currentZ=0;A.showComplete=1;CHECK(render_hash()==full,"MAP complete view retains upper levels from Z0");A.showComplete=0;CHECK(render_hash()!=full,"MAP single lower view differs from complete view");A.currentZ=1;A.showAllBelow=0;uint64_t single=render_hash();A.showAllBelow=1;CHECK(render_hash()!=single,"lower level visible from Z1 when enabled");A.showAllBelow=0;CHECK(render_hash()==single,"lower levels can be hidden again");
size_t cells=(size_t)A.map.x*A.map.y*A.map.z*sizeof(MapCell);void*before=malloc(cells);memcpy(before,A.map.cells,cells);A.selectedLib=0;A.blueprintMode=0;wndproc(A.hwnd,WM_RBUTTONDOWN,0,MAKELPARAM(A.sidebarW+200,400));CHECK(A.selectedLib==-1&&!A.painting&&!A.erasing,"right click releases a single piece");CHECK(!memcmp(before,A.map.cells,cells),"release does not erase map content");A.selectedLib=0;A.blueprintMode=1;wndproc(A.hwnd,WM_RBUTTONDOWN,0,MAKELPARAM(A.sidebarW+200,400));CHECK(A.selectedLib==-1&&A.blueprintMode==0,"right click releases an assembly");A.selectedLib=0;wndproc(A.hwnd,WM_KEYDOWN,VK_ESCAPE,0);CHECK(A.selectedLib==-1,"Escape releases a single piece");free(before);
A.clientH=1000;A.panelSplit1=TREE_TOP+55;A.panelSplit2=700;ensure_panel_splits();CHECK(A.panelSplit1==TREE_TOP+55,"left section splitter stays at its boundary");
int right=A.clientW-A.inspectorW;wndproc(A.hwnd,WM_LBUTTONDOWN,0,MAKELPARAM(right,300));wndproc(A.hwnd,WM_MOUSEMOVE,0,MAKELPARAM(A.clientW-420,300));CHECK(A.inspectorW==420,"right panel can be resized");wndproc(A.hwnd,WM_LBUTTONUP,0,0);wndproc(A.hwnd,WM_LBUTTONDOWN,0,MAKELPARAM(A.sidebarW,300));wndproc(A.hwnd,WM_MOUSEMOVE,0,MAKELPARAM(220,300));CHECK(A.sidebarW==220,"left panel can be narrowed below old 280 px limit");wndproc(A.hwnd,WM_LBUTTONUP,0,0);
BlueprintCapturePart protectedPart={.x=0,.y=0,.z=0,.layer=0,.lib=0,.local=1};CHECK(!editor_apply_batch(&protectedPart,1,0,0,0,0),"original MAP protected against batch edits");
A.map.path[0]=0;A.currentZ=0;A.showComplete=1;A.showAllBelow=1;A.brushMode=0;A.selectedLib=-1;
size_t upperBytes=(size_t)A.map.x*A.map.y*(A.map.z-1)*sizeof(MapCell);void*upper=malloc(upperBytes);memcpy(upper,A.map.cells+A.map.x*A.map.y,upperBytes);int erased=0;for(int y=180;y<A.clientH-60&&!erased;y+=8)for(int x=A.sidebarW+10;x<A.clientW-A.inspectorW&&!erased;x+=8)erased=erase_visible_piece_at(x,y);CHECK(erased,"eraser operates on an actual lower-level piece");CHECK(!memcmp(upper,A.map.cells+A.map.x*A.map.y,upperBytes),"complete-view erasing leaves all upper levels intact");free(upper);
handle_command(IDM_VIEW_TOP);CHECK(A.viewMode==1,"direct top-view command");handle_command(IDM_VIEW_ISO);CHECK(A.viewMode==2,"direct iso-plan command");handle_command(IDM_VIEW_NORMAL);CHECK(A.viewMode==0,"direct normal-view command");
A.sidebarW=300;A.inspectorW=300;A.currentZ=0;A.showComplete=1;A.showGrid=1;A.panX=-140;A.panY=160;A.panelSplit1=A.panelSplit2=0;screenshot(L"work/workshop-v280-normal.bmp");

int lib=-1;for(int i=0;i<A.libraryCount;i++)if(!_wcsicmp(A.library[i].name,L"SAND")&&A.library[i].source==SRC_TFTD){lib=i;break;}
CHECK(lib>=0,"original SAND fixture available");
CHECK(new_map(10,10,3),"create isolated test document");A.currentZ=1;A.viewMode=0;A.selectedLib=lib;A.selectedLocal=16;A.selectedLayer=0;E.replace=0;E.strokeGroup=0;
BlueprintCapturePart pp[2]={{.x=2,.y=2,.z=1,.layer=0,.lib=lib,.local=16},{.x=3,.y=2,.z=1,.layer=0,.lib=lib,.local=16}};
CHECK(editor_apply_batch(pp,2,0,0,0,0),"place two-part assembly atomically");
MapCell snapshot[300];memcpy(snapshot,A.map.cells,sizeof(snapshot));
CHECK(!editor_apply_batch(pp,2,0,0,0,0),"occupied destination rejected by default");CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"rejected placement preserves data");
CHECK(!editor_apply_batch(pp,2,7,0,0,0),"partially out of bounds assembly rejected");CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"no partial placement at map edge");
E.count=2;memcpy(E.parts,pp,sizeof(pp));CHECK(editor_begin_transform(1),"begin assembly move");editor_cancel();CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"cancelled move leaves original intact");
E.count=2;memcpy(E.parts,pp,sizeof(pp));CHECK(editor_begin_transform(1)&&editor_commit_transform(3,2,1),"overlapping assembly move succeeds");CHECK(!cell_at(2,2,1)->part[0]&&cell_at(3,2,1)->part[0]&&cell_at(4,2,1)->part[0],"overlap move keeps both parts");
do_undo();CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"one undo restores complete overlapping move");do_redo();CHECK(!cell_at(2,2,1)->part[0]&&cell_at(4,2,1)->part[0],"one redo reapplies complete move");do_undo();
plan_cell_at(5,2,1)->flags|=PLAN_FLAG_LOCKED;CHECK(!editor_apply_batch(pp,2,3,0,0,0),"locked target rejects whole assembly");CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"locked target causes no partial write");plan_cell_at(5,2,1)->flags=0;
E.count=2;memcpy(E.parts,pp,sizeof(pp));CHECK(editor_begin_transform(2)&&editor_commit_transform(2,4,2),"duplicate assembly onto another Z");CHECK(cell_at(2,2,1)->part[0]&&cell_at(2,4,2)->part[0]&&cell_at(3,4,2)->part[0],"duplication preserves source and layers");do_undo();CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"one undo removes whole duplicate only");
E.count=2;memcpy(E.parts,pp,sizeof(pp));editor_delete_selection();CHECK(!cell_at(2,2,1)->part[0]&&!cell_at(3,2,1)->part[0],"explicit delete removes whole selection");do_undo();CHECK(!memcmp(snapshot,A.map.cells,sizeof(snapshot)),"one undo restores deleted selection");

A.currentZ=1;A.showComplete=1;A.showAllBelow=1;E.scope=0;editor_frame();int hitx=-1,hity=-1;for(int sy=EDITOR_TOP;sy<A.clientH-30&&hitx<0;sy++)for(int sx=A.sidebarW+10;sx<A.clientW-A.inspectorW-10&&hitx<0;sx++){BlueprintCapturePart h;if(hit_piece_at_levels(sx,sy,&h.x,&h.y,&h.z,&h.layer,&h.lib,&h.local,1,1)&&h.x==2&&h.y==2){hitx=sx;hity=sy;}}
CHECK(hitx>=0,"visible piece can be located in actual projection");if(hitx>=0){editor_select_at(hitx,hity,0);CHECK(E.count==1&&E.parts[0].z==1,"selection click targets active Z");editor_select_at(hitx,hity,1);CHECK(E.count==0,"shift-click toggles selection off");}
int bi=-1,nparts=0;BlueprintCapturePart bp[EDITOR_CAP];for(int i=0;i<BLUEPRINT_RC15_COUNT;i++)if((nparts=editor_blueprint_parts(1,i,0,bp))>1&&nparts<20){bi=i;break;}CHECK(bi>=0,"resolvable Bible assembly available");
if(bi>=0){CHECK(scene_alloc(40,40,8),"allocate assembly recognition scene");for(int i=0;i<nparts;i++){bp[i].x+=15;bp[i].y+=15;bp[i].z+=3;}CHECK(editor_apply_batch(bp,nparts,0,0,0,0),"place actual Bible assembly");editor_recognize(bp[0]);CHECK(E.count>=nparts,"recognize complete Bible assembly from placed content");do_undo();scene_free();CHECK(new_map(10,10,3),"reset document after assembly test");}
pp[1].layer=99;CHECK(!editor_apply_batch(pp,2,0,4,0,0),"invalid physical slot rejected safely");pp[1]=pp[0];CHECK(!editor_apply_batch(pp,2,0,4,0,0),"duplicate destination within assembly rejected");
unsigned pixel=0x80abcdefu;editorRenderOpacity=50;editor_apply_opacity(&pixel);CHECK(pixel==0x40abcdefu,"ghost rendering preserves existing alpha");editorRenderOpacity=100;
A.currentZ=1;E.above=1;E.opacity=50;E.below=2;CHECK(editor_opacity_for_z(0)==55&&editor_opacity_for_z(1)==100&&editor_opacity_for_z(2)==50,"active level opaque with independent above/below ghosts");E.above=0;E.below=1;
A.selectedLib=lib;A.blueprintMode=1;editor_palette_selected();CHECK(A.blueprintMode==0&&E.tool==EDIT_PLACE&&E.count==0,"library selection always starts with one piece");
A.viewMode=1;E.planErase=0;editor_key('E',0);CHECK(E.planErase,"plan eraser explicitly activated with E");editor_cancel();CHECK(!E.planErase,"right-click equivalent cancels plan eraser");A.viewMode=0;
CHECK(scene_alloc(10,10,3),"create isolated scene test");pp[0].layer=0;pp[0].local=9999;CHECK(!editor_apply_batch(pp,1,0,0,0,0),"scene rejects invalid resource before mutation");pp[0].local=16;CHECK(editor_apply_batch(pp,1,0,0,0,0),"scene placement works without MAP palette limit");do_undo();CHECK(scene_cell_at(2,2,1)->lib[0]==-1,"scene placement undo");scene_free();

scene_free();A.selectedLib=lib;A.selectedLocal=16;editor_palette_selected();A.sidebarW=180;A.inspectorW=180;SetWindowPos(A.hwnd,NULL,0,0,860,600,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);ensure_backbuf(A.clientW,A.clientH);screenshot(L"work/workshop-v280-narrow.bmp");CHECK(A.clientW-A.sidebarW-A.inspectorW>=420,"minimum window retains usable central controls");

int riskLib=-1;for(int i=0;i<A.libraryCount;i++)if(!_wcsicmp(A.library[i].name,L"GRUNGE4")&&A.library[i].source==SRC_TFTD)riskLib=i;
CHECK(riskLib>=0&&editor_role(riskLib,26)!=NULL,"known original FLOOR equipment warning present");if(riskLib>=0){uint8_t*record=A.library[riskLib].mcdRaw+26*MCD_SIZE;uint8_t saved=record[40];record[40]^=1;CHECK(editor_role(riskLib,26)==NULL,"changed MCD never inherits an original visual role blindly");record[40]=saved;}

A.viewMode=1;screenshot(L"work/workshop-v280-plan-narrow.bmp");int pl=A.sidebarW+12,pw=(A.clientW-A.inspectorW-12-pl-20)/6;E.planErase=0;plan_toolbar_click(pl+2*(pw+4)+5,118);CHECK(E.planErase,"responsive PLAN Gomme button enables erasing");plan_toolbar_click(pl+3*(pw+4)+5,118);CHECK(A.viewMode==0,"responsive PLAN Pieces button returns to normal view");

A.viewMode=1;E.planPanelX=0;E.planPanelY=0;editor_plan_scroll(170,0);int panelLeft=A.clientW-A.inspectorW;A.planSemanticLayer=0;editor_plan_inspector_click(panelLeft+20,70);CHECK(A.planSemanticLayer==1,"narrow PLAN panel exposes offscreen object tab with matching hitboxes");E.planPanelX=0;E.planPanelY=100;A.brushSize=1;editor_plan_inspector_click(panelLeft+105,70);CHECK(A.brushSize==2,"scrolled PLAN size plus button matches displayed control");editor_plan_scroll(0,100);CHECK(E.planPanelY==200,"PLAN panel vertical scroll exposes lower controls");screenshot(L"work/workshop-v280-plan-scrolled.bmp");A.viewMode=0;
CHECK(dialogs==0,"no unexpected dialog during tests");printf("RESULT %d/%d checks passed\n",checks-failures,checks);return failures?1:0;
}
