/* Persistent GEO layer of a Workshop scene. No MCD or engine semantics invented. */
#pragma pack(push,1)
typedef struct {char id[96],uid[80];int32_t x,y,rotation,mirror,support,kind;float z;double controls[16],rise;} SceneGeoRecord;
typedef struct {uint32_t count,decorCount;} SceneGeoHeader;
#pragma pack(pop)
static size_t scene_geo_bytes(const SceneDoc*s){return s->geoCount?sizeof(SceneGeoHeader)+(size_t)s->geoCount*sizeof(SceneGeoRecord)+(size_t)s->geoDecorCount*sizeof(GeoDecor):0;}
static void scene_geo_write(uint8_t*b,const SceneDoc*s){SceneGeoHeader h={(uint32_t)s->geoCount,(uint32_t)s->geoDecorCount};memcpy(b,&h,sizeof(h));b+=sizeof(h);for(int n=0;n<s->geoCount;n++){const GeoInstance*i=&s->geo[n];SceneGeoRecord r={0};strncpy(r.id,geo_meshes[i->mesh].id,95);strncpy(r.uid,i->uid,79);r.x=i->x;r.y=i->y;r.z=i->z;r.rotation=i->rotation;r.mirror=i->mirror;r.support=i->support;if(i->dynamic){r.kind=i->dynamic->kind;r.rise=i->dynamic->rise;memcpy(r.controls,i->dynamic->controls,sizeof(r.controls));}memcpy(b,&r,sizeof(r));b+=sizeof(r);}if(s->geoDecorCount)memcpy(b,s->geoDecor,(size_t)s->geoDecorCount*sizeof(GeoDecor));}
static int scene_geo_index(SceneDoc*s){size_t n=(size_t)s->x*s->y*s->z;s->geoLookup=malloc(n*sizeof(int));if(!s->geoLookup)return 0;for(size_t j=0;j<n;j++)s->geoLookup[j]=-1;for(int j=0;j<s->geoCount;j++){GeoInstance*i=&s->geo[j];if(i->x<0||i->y<0||i->x>=s->x||i->y>=s->y||i->z<0||i->z>=s->z||i->z!=floorf(i->z))return 0;size_t k=((int)i->z*s->y+i->y)*s->x+i->x;if(s->geoLookup[k]>=0)return 0;s->geoLookup[k]=j;}return 1;}
static int scene_geo_read(const uint8_t*b,size_t size,SceneDoc*s){if(size<sizeof(SceneGeoHeader))return 0;SceneGeoHeader h;memcpy(&h,b,sizeof(h));if(!h.count||h.count>GEO_MAX||h.decorCount>512||size!=sizeof(h)+(size_t)h.count*sizeof(SceneGeoRecord)+(size_t)h.decorCount*sizeof(GeoDecor))return 0;b+=sizeof(h);s->geo=calloc(h.count,sizeof(GeoInstance));s->geoDecor=calloc(h.decorCount?h.decorCount:1,sizeof(GeoDecor));if(!s->geo||!s->geoDecor)return 0;s->geoCount=h.count;s->geoDecorCount=h.decorCount;
 for(int n=0;n<s->geoCount;n++){SceneGeoRecord r;memcpy(&r,b,sizeof(r));b+=sizeof(r);if(!memchr(r.id,0,sizeof(r.id))||!memchr(r.uid,0,sizeof(r.uid))||r.rotation<0||r.rotation>3||(r.mirror!=0&&r.mirror!=1)||(r.support!=0&&r.support!=1)||!isfinite(r.z))return 0;GeoInstance*i=&s->geo[n];i->mesh=geo_id(r.id);if(i->mesh<0)return 0;i->x=r.x;i->y=r.y;i->z=r.z;i->rotation=r.rotation;i->mirror=r.mirror;i->support=r.support;memcpy(i->uid,r.uid,80);if(r.kind){if(r.kind!=1&&r.kind!=2)return 0;GeoDynamic*d=calloc(1,sizeof(*d));if(!d)return 0;i->dynamic=d;d->kind=r.kind;d->rise=r.rise;memcpy(d->controls,r.controls,sizeof(d->controls));if(d->kind==1){for(int k=0;k<16;k++)if(!isfinite(d->controls[k])||d->controls[k]<0||d->controls[k]>1)return 0;}else if(!isfinite(d->rise)||d->rise<=0||d->rise>1)return 0;geo_dynamic_build(d,geo_meshes[i->mesh].id);}}
 if(s->geoDecorCount)memcpy(s->geoDecor,b,(size_t)s->geoDecorCount*sizeof(GeoDecor));for(int n=0;n<s->geoDecorCount;n++){GeoDecor*d=&s->geoDecor[n];if(d->x<0||d->y<0||d->x>=s->x||d->y>=s->y||!isfinite(d->z)||d->z<0||d->z>=s->z||(d->family!=0&&d->family!=1)||(d->family==0&&d->local!=0&&d->local!=3&&d->local!=5&&d->local!=8)||(d->family==1&&d->local!=0&&d->local!=1&&d->local!=10))return 0;}
 return scene_geo_index(s)&&geo_validate(s->geo,s->geoCount,1,0);
}
static float*sceneGeoDepth;static int*sceneGeoPick;static size_t sceneGeoCapacity;
static void scene_geo_draw(int x,int y,int z,int sx,int sy){int owner=A.scene.geoLookup[(z*A.scene.y+y)*A.scene.x+x];if(owner<0)return;GeoInstance*i=&A.scene.geo[owner];const GeoMesh*m=geo_mesh(i);size_t n=(size_t)A.backW*A.backH;if(n>sceneGeoCapacity){free(sceneGeoDepth);free(sceneGeoPick);sceneGeoDepth=malloc(n*sizeof(float));sceneGeoPick=malloc(n*sizeof(int));sceneGeoCapacity=sceneGeoDepth&&sceneGeoPick?n:0;}if(!sceneGeoCapacity)return;
 GeoVec world[2048],screen[2048];int x0=A.backW,y0=A.backH,x1=0,y1=0;for(int k=0;k<m->nv;k++){world[k]=geo_transform(m->v[k],i);GeoVec v=world[k];float px=sx+16*A.zoom+(v.x-x-v.y+y)*16*A.zoom,py=sy+24*A.zoom+(v.x-x+v.y-y)*8*A.zoom-(v.z-z)*24*A.zoom;screen[k]=(GeoVec){px,py,v.x+v.y+v.z*(2.f/3.f)};x0=min(x0,(int)floorf(px));y0=min(y0,(int)floorf(py));x1=max(x1,(int)ceilf(px));y1=max(y1,(int)ceilf(py));}
 x0=max(0,x0);y0=max(0,y0);x1=min(A.backW-1,x1);y1=min(A.backH-1,y1);for(int yy=y0;yy<=y1;yy++)for(int xx=x0;xx<=x1;xx++)sceneGeoDepth[(size_t)yy*A.backW+xx]=-1e9f;
 uint32_t*oldP=GEO.pixels;float*oldD=GEO.depth;int*oldI=GEO.pick;int ow=GEO.bw,oh=GEO.bh,sel=GEO.selected;GEO.pixels=A.backbuf;GEO.depth=sceneGeoDepth;GEO.pick=sceneGeoPick;GEO.bw=A.backW;GEO.bh=A.backH;GEO.selected=-1;int oldOpacity=geoRasterOpacity;geoRasterOpacity=editorRenderOpacity;RhTexture*top=NULL,*side=NULL;top=rh_texture(0);side=rh_texture(1);for(int k=0;k<m->nt;k++){GeoTri t=m->t[k];geo_triangle(screen[t.a],screen[t.b],screen[t.c],world[t.a],world[t.b],world[t.c],t.zone,owner,t.zone?side:top);}GEO.pixels=oldP;GEO.depth=oldD;GEO.pick=oldI;GEO.bw=ow;GEO.bh=oh;GEO.selected=sel;geoRasterOpacity=oldOpacity;
 for(int k=0;k<A.scene.geoDecorCount;k++){GeoDecor*d=&A.scene.geoDecor[k];if(d->x!=x||d->y!=y||floorf(d->z)!=z)continue;int lib=library_find_name_ctx(d->family?L"ROCKS":L"WEEDS",SRC_TFTD,L"TFTD ORIGINAL");if(lib>=0&&library_load(lib))draw_sprite_scaled(lib,d->local,mcd_frame(lib,d->local),sx,sy-(int)lroundf((d->z-z)*24*A.zoom),A.zoom);}
}
