#include "workshop_tutorial_data.h"
static HWND tutorialWindow,tutorialList,tutorialText;
static HFONT tutorialFont;
static void tutorial_refresh(void){if(!tutorialWindow)return;int n=(int)SendMessageW(tutorialList,LB_GETCURSEL,0,0);if(n<0)n=0;SendMessageW(tutorialList,LB_RESETCONTENT,0,0);for(unsigned i=0;i<sizeof(tutorialChapters)/sizeof(*tutorialChapters);i++)SendMessageW(tutorialList,LB_ADDSTRING,0,(LPARAM)tutorialChapters[i].title[i18nLanguage]);SendMessageW(tutorialList,LB_SETCURSEL,n,0);SetWindowTextW(tutorialText,tutorialChapters[n].body[i18nLanguage]);SetWindowTextW(tutorialWindow,tr(L"Tuto"));}
static LRESULT CALLBACK tutorial_wndproc(HWND h,UINT msg,WPARAM wp,LPARAM lp){switch(msg){case WM_CREATE:tutorialWindow=h;tutorialList=CreateWindowExW(WS_EX_CLIENTEDGE,L"LISTBOX",L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|LBS_NOTIFY,0,0,280,500,h,(HMENU)1,GetModuleHandleW(NULL),NULL);tutorialText=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|ES_MULTILINE|ES_READONLY|ES_AUTOVSCROLL,280,0,700,500,h,(HMENU)2,GetModuleHandleW(NULL),NULL);tutorialFont=CreateFontW(-18,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");SendMessageW(tutorialList,WM_SETFONT,(WPARAM)tutorialFont,TRUE);SendMessageW(tutorialText,WM_SETFONT,(WPARAM)tutorialFont,TRUE);tutorial_refresh();return 0;
case WM_SIZE:{int w=LOWORD(lp),hh=HIWORD(lp),left=min(400,max(250,w/3));MoveWindow(tutorialList,10,10,left-20,max(10,hh-20),TRUE);MoveWindow(tutorialText,left,10,max(10,w-left-10),max(10,hh-20),TRUE);return 0;}
case WM_COMMAND:if(LOWORD(wp)==1&&HIWORD(wp)==LBN_SELCHANGE){int n=(int)SendMessageW(tutorialList,LB_GETCURSEL,0,0);if(n>=0&&(unsigned)n<sizeof(tutorialChapters)/sizeof(*tutorialChapters))SetWindowTextW(tutorialText,tutorialChapters[n].body[i18nLanguage]);return 0;}break;
case WM_DESTROY:DeleteObject(tutorialFont);tutorialFont=NULL;tutorialWindow=tutorialList=tutorialText=NULL;return 0;
}return DefWindowProcW(h,msg,wp,lp);}
static void tutorial_open(void){if(tutorialWindow){SetForegroundWindow(tutorialWindow);return;}static int registered;if(!registered){WNDCLASSW wc={0};wc.lpfnWndProc=tutorial_wndproc;wc.hInstance=GetModuleHandleW(NULL);wc.lpszClassName=L"WorkshopTutorial";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_BTNFACE+1);RegisterClassW(&wc);registered=1;}HWND h=CreateWindowExW(WS_EX_TOOLWINDOW,L"WorkshopTutorial",tr(L"Tuto"),WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1250,800,A.hwnd,NULL,GetModuleHandleW(NULL),NULL);ShowWindow(h,SW_SHOW);UpdateWindow(h);}
